### ISSUE TITLE
Add stopwords for frequencies

### ISSUE THREAD

**Issue by mebrett** [omeka/plugin-Ngram#20]
One thing I'm noticing about the ngram frequencies is that it's returning a lot of ngrams (uni,bi,tri) of stop words (of the, on the, for the, on a, in a, etc). Is there a list of stopwords built in? Can we add one - ideally one that users of the plugin could modify (on the server side is fine) to add in specific stopwords or switch from English to French, for example.

**Comment by jimsafley** [comment]
Removing any words from a corpus results in inaccurate relative frequencies. Stopwords and ngrams typically don't mesh since they produce ngrams that otherwise don't exist in the corpus.

**Comment by zerocrates** [comment]
To do stopwords accurately you'd have to not simply drop them but replace them with some marker and then drop any generated ngrams the marker participates in, or otherwise wait to apply the stop list until the ngram is generated. Even then you'd lose valuable information in the form of ngrams that contained just one stop word and wouldn't likely be seen as noise.

The only possibly reasonable thing I can think of would be to drop the ngrams only if they were composed _entirely_ of stopwords (and this obviously doesn't do anything about the frequency issue).

**Comment by mebrett** [comment]
If nothing else, we'll mention this in the documentation as a reason not to do a frequency with fewer than 100 results

**Comment by mebrett** [comment]
Would it be possible to strip out html markup from the text of the field?

**Comment by jimsafley** [comment]
It is possible, though I hesitate to implement any preprocessing steps on the corpus. I'll look into this further.

**Comment by jimsafley** [comment]
@mebrett Would you make a separate issue about stripping HTML? After some thought, I think it's worth looking at more closely.

**Comment by jimsafley** [comment]
We're not going to implement stopwords for reasons specified above. I agree that we should add a note in documentation to expect a prevalence of ngrams regarded as stopwords.
